In [2]:
from gensim.corpora.wikicorpus import extract_pages

In [ ]:
from trec.treccorpus import TrecCorpus
fname = "/home/mike/Documents/corpus/Trec1&2/fr88.dat"
fname2 = "/home/mike/Documents/corpus/Trec7/fr94/fr94.dat"
# temp = extract_pages(fname)
# print(temp)

In [ ]:
for title, text, pid in temp:
    print(text)
    print(pid)
    break

In [ ]:
try:
    from xml.etree.cElementTree import iterparse
except ImportError:
    from xml.etree.ElementTree import iterparse
import xml.etree.cElementTree as ET
from xml.etree.cElementTree import XMLParser
def extract_docs(f):
    parser = XMLParser(recover=True)
    # tree = ET.fromstring(f)
    #elems = (elem for _, elem in iterparse(f, events=("DOC",)))
    #elems = (elem for _, elem in iterparse(f, events=("start","end")))
    content = iterparse(f,events=("start",), parser=parser)
    # print(next(elems))
    # fulltext = ""
    # root = tree.getroot()
    # for child in root:
    #     print(child.tag, child.attrib)
    for event, elem in content:
        tag = elem.tag
        text = elem.text
        print(tag, text)
        # if tag == "DOCNO":
        #     print(text)
        # elif tag == "TEXT":
        #     print(text)
        # print (tag)
        # text = elem.find("TEXT").text
        # id = elem.find("DOCNO")
        # print(text)
        # print(id)

In [ ]:
extract_docs(fname)

In [ ]:
from lxml.etree import iterparse as ip

In [ ]:
def extract(f):
    content = ip(f,events=("start",),
                 tag=("DOCNO","TEXT"),
                 load_dtd=False,
                 remove_blank_text=True,
                 html=False,
                 recover=True,
                 encoding='utf-8')
    for event, elem in content:
        print(elem.tag, elem.text)

In [ ]:
extract(fname)

In [ ]:
from bs4 import BeautifulSoup as Bs
with open(fname2) as fp:
    soup = Bs(fp, features='lxml')
    for elem in soup.find_all('docno'):
        # if(elem.tag == "DOCNO"):
        print(elem)

In [9]:
from trec.treccorpus import TrecCorpus
pname = "f:/Corpus/trectest/"
trecc = TrecCorpus(pname, dictionary={}, metadata=True)
text, docno = trecc.get_texts()
print(docno, text)

AttributeError: 'str' object has no attribute 'readline'

In [8]:
def test():
    for i in range(0,10):
        yield i

a = test()
next(a)
next(a)
next(a)

0

In [1]:
%%time
from trec.treccorpus import TrecCorpus
pname = "f:/Corpus/trectest/"
trecc = TrecCorpus(pname, dictionary={}, metadata=True)
count = 0
for i in trecc:
    count+=1
print(count)

AttributeError: 'dict' object has no attribute 'doc2bow'

In [42]:
from trec.treccorpus import TrecCorpus
pname = r"/home/mike/Documents/corpus/trectest/"
trecc = TrecCorpus(pname, dictionary={}, metadata=True)
text, docno = trecc.get_texts()
print(docno, text)

ImportError: cannot import name 'logsumexp'

In [5]:
for title, text, pid in temp:
    print(text)
    print(pid)
    break

ValueError:  not recognized as MediaWiki dump namespace

In [50]:
try:
    from xml.etree.cElementTree import iterparse
except ImportError:
    from xml.etree.ElementTree import iterparse
import xml.etree.cElementTree as ET
from xml.etree.cElementTree import XMLParser
def extract_docs(f):
    parser = XMLParser(recover=True)
    # tree = ET.fromstring(f)
    #elems = (elem for _, elem in iterparse(f, events=("DOC",)))
    #elems = (elem for _, elem in iterparse(f, events=("start","end")))
    content = iterparse(f,events=("start",), parser=parser)
    # print(next(elems))
    # fulltext = ""
    # root = tree.getroot()
    # for child in root:
    #     print(child.tag, child.attrib)
    for event, elem in content:
        tag = elem.tag
        text = elem.text
        print(tag, text)
        # if tag == "DOCNO":
        #     print(text)
        # elif tag == "TEXT":
        #     print(text)
        # print (tag)
        # text = elem.find("TEXT").text
        # id = elem.find("DOCNO")
        # print(text)
        # print(id)

In [51]:
extract_docs(fname)

TypeError: 'recover' is an invalid keyword argument for this function

In [1]:
from lxml.etree import iterparse as ip

In [20]:
def extract(f):
    content = ip(f,events=("start",),
                 tag=("DOCNO","TEXT"),
                 load_dtd=False,
                 remove_blank_text=True,
                 html=False,
                 recover=True,
                 encoding='utf-8')
    for event, elem in content:
        print(elem.tag, elem.text)

In [21]:
extract(fname)

DOCNO  FR88101-0001 
TEXT None


In [40]:
from bs4 import BeautifulSoup as Bs
with open(fname2) as fp:
    soup = Bs(fp, features='lxml')
    for elem in soup.find_all('docno'):
        # if(elem.tag == "DOCNO"):
        print(elem)

<docno> FR940104-0-00001 </docno>
<docno> FR940104-0-00002 </docno>
<docno> FR940104-0-00003 </docno>


In [2]:
from trec.treccorpus import TrecCorpus
pname = r"/home/mike/Documents/corpus/trectest/"
trecc = TrecCorpus(pname, dictionary={}, metadata=True)
text, docno = trecc.get_texts()
print(docno, text)

No input document stream provided; assuming dictionary will be initialized some other way.


FileNotFoundError: [Errno 2] No such file or directory: 'doe.dat'

In [9]:
from trec.trecqrels import TrecQrels
path = "f:/Runs/qrels/"
tq = TrecQrels(path)
tq.init()
for doc_no, topic_no, is_rel in tq.get_texts():
    print(topic_no)
# tq.get_doc_list("51")

KeyError: '101'

In [18]:
import tensorflow as tf

# y_true = [[0.0, 1.0], [1.0, 0.0]]
# y_pred = [[0.0, 1.0], [1.0, 0.0]]

# y_true = [[0.6, 0.4], [0.4, 0.6]]
# y_pred = [[0.6, 0.4], [0.4, 0.6]]
# 
# mse = tf.keras.losses.MeanSquaredError()
# mse(y_true, y_pred).numpy()

y_true = [1, 2]
y_pred = [[0.05, 0.95, 0.0], [0.1, 0.8, 0.1]]
          
scce = tf.keras.losses.SparseCategoricalCrossentropy()
scce(y_true, y_pred).numpy()

# bce = tf.keras.losses.CategoricalCrossentropy(from_logits=False, reduction=tf.keras.losses.Reduction.NONE)
# bce(y_true, y_pred).numpy()

AttributeError: 'list' object has no attribute 'op'

In [19]:
import numpy as np
from scipy.sparse import csc_matrix

row = np.array([0, 1])
col = np.array([0, 1])
data = np.array([1.0, 1.0])


# y_true = [[0.6, 0.4], [0.4, 0.6]]
y_true = [[0.0, 1.0], [1.0, 0.0]]
# y_pred = [[0.6, 0.4], [0.4, 0.6]]
y_pred = csc_matrix((data, (row, col)), shape=(2, 2)).toarray().tolist()

mse = tf.keras.losses.MeanSquaredError()
mse(y_true, y_pred).numpy()

1.0

In [16]:
import numpy as np
from scipy.special import softmax
from sklearn.preprocessing import normalize
np.set_printoptions(precision=5)

arr1 = np.array([0,2,0,0,4,0,0,8,0,0])
arr2 = np.array([1,1,0,0,4,0,0,3,0,1])
arr3 = np.array([0,0,0,0,0,0,0,0,0,1])
# int_array = np.array([0,0,3,4,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
print(normalize(np.array([arr1]), norm='max'))
# print(arr1+arr2)
# print(softmax(arr1))
# print(softmax(arr2))
# print(softmax(arr1+arr2))
# print(softmax(arr1)+softmax(arr2))

print(softmax(arr3))

[[0.   0.25 0.   0.   0.5  0.   0.   1.   0.   0.  ]]
[0.08534 0.08534 0.08534 0.08534 0.08534 0.08534 0.08534 0.08534 0.08534
 0.23197]


In [51]:
from scipy.sparse import coo_matrix

a=coo_matrix((3,4), dtype=np.int8)
print(a.getrow(2).toarray())

[[0 0 0 0]]


In [53]:
from scipy.sparse import csr_matrix

indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 2, 1])
data = np.array([1, 2, 3, 4, 6, 5])
csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [58]:
docs = [["hello", "world", "hello"], ["goodbye", "cruel", "world"]]
indptr = [0]
indices = []
data = []
vocabulary = {}
for d in docs:
    for term in d:
        index = vocabulary.setdefault(term, len(vocabulary))
        indices.append(index)
        data.append(1)
    indptr.append(len(indices))
csr_matrix((data, indices, indptr), dtype=int).toarray()

array([[2, 1, 0, 0],
       [0, 1, 1, 1]])

In [1]:
a = [1,5,4,3]
b = a.sort()
b

In [21]:
a = [1,2,3,4]
b = tf.keras.layers.Dense(units=4, activity_regularizer=tf.keras.regularizers.l1)(a)
b

ValueError: Layer dense_1 expects 1 inputs, but it received 4 input tensors. Inputs received: [<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=4>]

In [2]:
%%time
from trec.treccorpus import TrecCorpus

pname = "f:/Corpus/trectest/"
trecc = TrecCorpus(pname, dictionary={})
sfile = "f:/Corpus/savetest.dat"
trecc.save_to_file(sfile)

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
Wall time: 4min 21s
